import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import React, { useCallback, useState } from "react";
import { useDropzone } from "react-dropzone";

const snarkjs = require("snarkjs");
// console.log(snarkjs.zKey.contribute);

enum Stage {
  PREV_ZKEY,
  ENTROPY,
  CONTRIBUTING,
  FINISHED, // download ready
}

// TODO: change back to 50 after testing
const DESIRED_ENTROPY_LEN = 2;

export default function Home() {
  const [stage, setStage] = useState<Stage>(Stage.PREV_ZKEY);

  const [prevZkeyBytes, setPrevZkeyBytes] = useState<Uint8Array | null>(null);
  const [entropy, setEntropy] = useState<string[]>([]);

  const onDrop = useCallback((files: File[]) => {
    console.log("Accepted prev zkey: ", files[0]);

    console.log("reading bytes");
    const reader = new FileReader();

    reader.onabort = () => console.log("file reading was aborted");
    reader.onerror = () => console.log("file reading has failed");
    reader.onload = () => {
      // Do whatever you want with the file contents
      const binaryStr = reader.result as ArrayBuffer;
      console.log("Finished reading!");
      console.log("length", binaryStr.byteLength);
      setPrevZkeyBytes(new Uint8Array(binaryStr));

      setStage(Stage.ENTROPY);
    };
    reader.readAsArrayBuffer(files[0]);
  }, []);
  const { getRootProps, getInputProps, isDragActive } = useDropzone({ onDrop });

  const handleEntropyKeyDown = async (
    event: React.KeyboardEvent<HTMLInputElement>
  ) => {
    const newEntropy = [...entropy, event.key];
    setEntropy(newEntropy);

    if (entropy.length >= DESIRED_ENTROPY_LEN) {
      console.log(`all set! ${DESIRED_ENTROPY_LEN} keys collected1`);
      setStage(Stage.CONTRIBUTING);
      await runContribution();
    }
  };

  const runContribution = async () => {
    console.log("Running zkey contribution w/ entropy: ", entropy);
    const ret = await snarkjs.zKey.contribute(
      prevZkeyBytes,
      "new.zkey", // TODO: how could this be opened by downstream lib?
      "dummy name", // TODO: name by contributor?
      entropy.join("")
    );

    console.log("Result: ", ret);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Personae Labs setup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Personae Lab trusted setup</h1>

        {/* based on stage, get zkey or get entropy or run contribution or download */}
        <div className={styles.description}>
          {stage === Stage.PREV_ZKEY && (
            <div {...getRootProps()}>
              <input {...getInputProps()} />
              {isDragActive ? (
                <p>Drop files here</p>
              ) : (
                <p>Click me to add the prev zkey file</p>
              )}
            </div>
          )}

          {stage === Stage.ENTROPY && (
            <div onKeyDown={handleEntropyKeyDown} tabIndex={0}>
              <div>
                <p>Click me, then type random characters for entropy.</p>
                <p>Fight muscle memory! The more random the better</p>
              </div>
            </div>
          )}

          {/* This phase is basically just running snarkjs stuff in the bg */}
          {stage === Stage.CONTRIBUTING && (
            <div>
              <p>Entropy collected! Computing phase2 contribution...</p>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
